Update bbu

diff --git a/bbu b/bbu
--- a/bbu
+++ b/bbu
@@ -12,8 +12,11 @@
 # Declare static variables:
 
 user=$USER
-
 host=$HOSTNAME
+backupdirectory=/media/"$user"/BU_Drive/BU_Backups/"$host"
+backupdrive=/media/"$user"/BU_Drive/
+RSYNC_CMD='sudo rsync -aH --delete --info=progress2'
+DEFAULT_BACKUP_DIRS='/etc /home'
 
 # Check for less and rsync, install if needed:
 
@@ -51,15 +54,18 @@ fi
 
 }
 
-check_exclude() {
+add_exclude() {
     if [ -f /bu.exclude ]; then
-        exit 0
+        exit RSYNC_CMD += "--exclude-from=bu.exclude"
     else
-        exit 1
+        exit RSYNC_CMD += ""
 }
 
-check_include(){
-
+add_include(){
+    if [ -f /bu.include ]; then
+        exit RSYNC_CMD += "--files-from=bu.include"
+    else
+        exit RSYNC_CMD += ""
 }
 
 apt_backup(){
@@ -76,225 +82,56 @@ cron_backup(){
 
 backup() {
 
-# Check for sudo privilages:
+	# Check for sudo privilages:
 
-echo "Checking for sudo privileges..."
-sudo ls >/dev/null
+	echo "Checking for sudo privileges..."
+	sudo ls >/dev/null
 
-# Making sure user has ownership of the BU_Drive:
+	# Making sure user has ownership of the BU_Drive:
 
-echo "Changing ownership of BU_Drive to $user..."
-sudo chown "$user" /media/"$user"/BU_Drive/
+	echo "Changing ownership of BU_Drive to $user..."
+	sudo chown "$user" /media/"$user"/BU_Drive/
 
-# Creating machine specific directories:
-echo "Checking for/creating machine specific directories..."
-mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"
+	# Creating machine specific directories:
+	echo "Checking for/creating machine specific directories..."
+	mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"
 
-# Check if directory for host machine was successfully created:
+	# Check if directory for host machine was successfully created:
 
-if mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"; then
+	if mkdir -p /media/"$user"/BU_Drive/BU_Backups/"$host"; then
 
-    echo "...Done. BU_Drive is ready."
+		echo "...Done. BU_Drive is ready."
 
-else
+	else
 
-    echo $'\n'$"BU Error: Could not create directroy for $host!" >&2
-    echo "- Backup aborted. Check the status of the BU_Drive." >&2
-    exit 1
-fi
+		echo $'\n'$"BU Error: Could not create directroy for $host!" >&2
+		echo "- Backup aborted. Check the status of the BU_Drive." >&2
+		exit 1
+	fi
 
-# Run rsync command:
+	# Run rsync command:
 
-echo "Backing up /etc and /home to BU_Drive/BU_Backups/$host/..."
+		echo "Backing up /etc and /home to BU_Drive/BU_Backups/$host/..."
 
-# Check for status of backup and exit:
-if check_exclude; then
-    if sudo rsync -aH --delete --info=progress2 --exclude-from=bu.exclude /etc /home /media/"$user"/BU_Drive/BU_Backups/"$host"/; then
+	# Check for status of backup and exit:
+	if sudo rsync -aH --delete --info=progress2 --exclude-from=bu.exclude /etc /home /media/"$user"/BU_Drive/BU_Backups/"$host"/; then
 
-        # Clear any accidental input during backup:
-        read -r -t 1 -n 10000 discard
-        echo "------------------"
-        echo "- All backed up! -"
-        echo "------------------"
-        echo "Wait! Syncing Drives..."
-        sync
-        echo "...done"
-        echo "It's safe to remove the USB drive now."
-        exit
-
-    else
-
-        # Clear any accidental input during backup:
-        read -r -t 1 -n 10000 discard
-        echo "There were errors! Try running the caoomnd again to correct them." >&2
-        echo "- If errors persist then you may have corrupt files or failing hardware." >&2
-        exit 1
-
-    fi
-else
-    if sudo rsync -aH --delete --info=progress2 /etc /home /media/"$user"/BU_Drive/BU_Backups/"$host"/; then
-
-            # Clear any accidental input during backup:
-            read -r -t 1 -n 10000 discard
-            echo "------------------"
-            echo "- All backed up! -"
-            echo "------------------"
-            echo "Wait! Syncing Drives..."
-            sync
-            echo "...done"
-            echo "It's safe to remove the USB drive now."
-            exit
-
-    else
-
-        # Clear any accidental input during backup:
-        read -r -t 1 -n 10000 discard
-        echo "There were errors! Try running the caoomnd again to correct them." >&2
-        echo "- If errors persist then you may have corrupt files or failing hardware." >&2
-        exit 1
-
-    fi
-fi
+		# Clear any accidental input during backup:
+		read -r -t 1 -n 10000
+		echo "Wait! Syncing Drives..."
+		sync
+		echo "...done"
+		exit
+	else
+		# Clear any accidental input during backup:
+		read -r -t 1 -n 10000
+		echo "There were errors! Try running the caoomnd again to correct them." >&2
+		echo "- If errors persist then you may have corrupt files or failing hardware." >&2	
+		exit 1
+	fi
 }
-
-restore() {
-# Runs an rsync operation to restore host's /home directory.
-# Check for the host's backup directory:
-
-    if [ ! -d /media/"$user"/BU_Drive/BU_Backups/"$host"/ ]; then
-
-        echo "BU Error: Cannot find valid backup directory for $host!" >&2
-        echo "- This drive may not have been used to backup this machine." >&2
-        echo "- BU_Backups/$host directory may have been moved or deleted." >&2
-        echo "- Hostneme or username may have changed since last backup." >&2
-        exit 1
-
-    fi
-
-    echo $'\n'$"BU Restore Function (Version 1.0)"
-    echo $'\n'$"WARNING!"
-    echo "Any new files created in /home since last backup WILL BE DELETED!"
-    echo "Are you sure you want to restore now? [y/N]"
-    read -r -n 1 -s choice
-
-    if [ "$choice" == "y" ]; then
-
-        # Giving user a chance to close other apps and starting rsync.
-        echo "Close any running applications and press any key to continue."
-        read -r -n 1 -s
-        echo $'\n'$"Restoring /home... Please DO NOT open any applications."
-        
-
-            # Checking status of rsync exit code:
-            if sudo rsync -aH --delete --info=progress2 /media/"$user"/BU_Drive/BU_Backups/"$host"/home/ /home/; then
-
-                # Prompt user to restart machine and exit:
-                # Clear any accidental input during restore:
-                read -r -t 1 -n 10000 discard
-                echo "Wait! Syncing drives..."
-                sync
-                echo "...Done."
-                echo "-------------------------"
-                echo "- Restoration Complete! -"
-                echo "-------------------------"
-                echo "It's now safe to remove BU_Drive."
-                echo "Restart machine for all changes to take effect."
-                exit
-            else
-                # Returning to Main Menu if rsync fails:
-                # Clear any accidental input during restore:
-                read -r -t 1 -n 10000 discard
-                echo $'\n'$"BU Error: rsync exited with errors!" >&2
-                echo "DO NOT EXIT XBT UNTIL YOU:" >&2
-                echo $'\n'$"    Make sure BU_Drive USB is still plugged in." >&2
-                echo "    Remount XBT Drive USB by unplugging it and plugging it back in." >&2
-                echo $'\n'$"Wait a few seconds and try running 'bu --restore' again." >&2
-                echo "You may need to manually restore your data if errors persist." >&2
-                exit 1
-            fi
-
-    else
-
-        echo "Restoration canceled."
-        exit
-
-    fi
-
-}
-
-help() {
-
-# Print help information using less utility:
-
-less << _EOF_
-BU - USB Backup Tool (Version 1.0) -- Help
-(v. 1.0)
-Press "q" to exit this Help page.
-Commands:
-bu = Fully backs up host's /etc and /home directories to BU_Drive.
-bu --help = Prints this help information.
-bu --restore = Accesses BU Restore function.
-Description:
-BU is a program that makes keeping all of your user data safely backed up on
-a dedicated External USB drive easy.
-BU will update files that have changed, remove files that have been
-deleted and add any new files that have been created since the last backup.
-The initial backup can take a lot of time if you have a lot of data stored
-in your system's /home directory. BU creates a directory with the host name
-of the machine it's backing up from inside BU_Backups. This allows users to
-share one BU_Drive with multiple machines.
-The directory structure and all files are stored openly to allow users easy
-access if they only need to retrieve a few files or directories using a file
-manager.
-The BU Restore function is an interactive tool that let's users restore their
-/home directories to a backup up state. This function will only work when
-restoring to a machine with the exact same hostname as the one the backs were
-made from. It is intended for emergency use, as when significant number of
-directories and files are accidentally removed from /home.
-BU_Drive Setup
-You need to prepare a BU Drive with a tool like Gparted or Disks.
-This can be any USB storage device. The dedicated USB drive MUST contain a
-partition formatted with a Linux native file system such as Ext4 or XFS. The
-partition MUST be labeled "BU_Drive" so BU can find it and use it for backups.
-The partition needs to have enough free capacity to store all data in /home on
-all of the machines you want to use the drive for. Note: You will get many
-errors if you attempt to use BU to backup to a partition that is formatted with
-non-native file systems like FAT32 or NTFS. 
-Disclaimer:
-THIS SOFTWARE IS PROVIDED BY EZEELINUX "AS IS" AND ANY EXPRESS OR IMPLIED
-WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
-EVENT SHALL EZEELINUX BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
-EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
-BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
-IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
-ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-POSSIBILITY OF SUCH DAMAGE.
-_EOF_
-}
-
-# Execution.
-
-# Checking for command line arguments:
-
-if [ "$1" == "--help" ]; then
-	help
-	exit
-fi
-
-if [ "$1" == "--restore" ]; then
-	drive_test
-	restore
-fi
-
-if  [ -n "$1"  ]; then
-    echo "BU Error: Invalid argument. " >&2
-    echo "- Try 'bu --help' to see the available commands. :)" >&2
-    exit 1
-fi
-
-echo "BU - USB Backup Tool (Version 1.0)"
 
 drive_test
+add_include
+add_exclude
 backup
